[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
admin_passwd = admin_password
db_host = host.docker.internal
db_port = 5432
db_user = facebook_init
db_password = face
db_name = facebook_odoo_integration
dbfilter = facebook_odoo_integration

